
name_dict = {
	"Arsenal": "Arsenal",
	"Aston Villa": "Aston Villa",
	"Bournemouth": "AFC Bournemouth",
	"Brighton": "Brighton & Hove Albion",
	"Burnley": "Burnley",
	"Cardiff": "Cardiff City",
	"Chelsea": "Chelsea",
	"Crystal Palace": "Crystal Palace",
	"Everton": "Everton",
	"Fulham": "Fulham",
	"Huddersfield": "Huddersfield Town",
	"Hull": "Hull City",
	"Leeds": "Leeds United",
	"Leicester": "Leicester City",
	"Liverpool": "Liverpool",
	"Man City": "Manchester City",
	"Man United": "Manchester United",
	"Middlesbrough": "Middlesbrough",
	"Newcastle": "Newcastle United",
	"Norwich": "Norwich City",
	"QPR": "Queens Park Rangers",
	"Sheffield United": "Sheffield United",
	"Southampton": "Southampton",
	"Stoke": "Stoke City",
	"Sunderland": "Sunderland",
	"Swansea": "Swansea City",
	"Tottenham": "Tottenham Hotspur",
	"Watford": "Watford",
	"West Brom": "West Bromwich Albion",
	"West Ham": "West Ham United",
	"Wolves": "Wolverhampton Wanderers"
}