
name_dict = {
    'Arsenal': 'Arsenal',
    'Leeds': 'Leeds United',
    'Brighton': 'Brighton & Hove Albion',
    'Crystal Palace': 'Crystal Palace',
    'Southampton': 'Southampton',
    'Wolves': 'Wolverhampton Wanderers',
    'Aston Villa': 'Aston Villa',
    'Liverpool': 'Liverpool',
    'West Ham': 'West Ham United',
    'Man City': 'Manchester City',
    'Burnley': 'Burnley',
    'Newcastle': 'Newcastle United',
    'Everton': 'Everton',
    'Man United': 'Manchester United',
    'Tottenham': 'Tottenham Hotspur',
    'Chelsea': 'Chelsea',
    'Leicester': 'Leicester City',
    'West Brom': 'West Bromwich Albion',
    'Fulham': 'Fulham',
    'Sheffield United': 'Sheffield United',
    'QPR': 'Queens Park Rangers',
    'Swansea': 'Swansea City',
    'Stoke': 'Stoke City',
    'Hull': 'Hull City',
    'Sunderland': 'Sunderland',
    'Watford': 'Watford',
    'Norwich': 'Norwich City',
    'Bournemouth': 'AFC Bournemouth',
    'Middlesbrough': 'Middlesbrough',
    'Huddersfield': 'Huddersfield Town',
    'Cardiff': 'Cardiff City',
}