name: Python format

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Format and organize code
        run: |
          isort . --recursive --atomic
          black . --line-length 79
      - name: Commit and push changes
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git add .
          git commit -m "Format and organize code with black and isort" || echo "No changes to commit"
          git push
