name: Update predictions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
    - timezone: 'America/Santiago'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
        
    - name: Run script
      run: |
        export PYTHONPATH=$PWD
        pipenv run python3 src/predict.py
        
    - name: Commit and push changes
      run: |
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_NAME }}"
        git add .
        git commit -m "Auto commit: Update predictions" || echo "No changes to commit"
        git push
